<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefineConstants>$(DefineConstants);WA1GONLIB</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Include="JADE.md" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../HamBusLog.csproj" Aliases="HamBusLog" />
  </ItemGroup>

</Project>